{"name": "Class CertStoreException", "module": "java.base", "package": "java.security.cert", "text": "An exception indicating one of a variety of problems retrieving\n certificates and CRLs from a CertStore.\n \n A CertStoreException provides support for wrapping\n exceptions. The getCause method returns the throwable,\n if any, that caused this exception to be thrown.\n \nConcurrent Access\n\n Unless otherwise specified, the methods defined in this class are not\n thread-safe. Multiple threads that need to access a single\n object concurrently should synchronize amongst themselves and\n provide the necessary locking. Multiple threads each manipulating\n separate objects need not synchronize.", "codes": ["public class CertStoreException\nextends GeneralSecurityException"], "fields": [], "methods": []}