{"name": "Class ClosedConnectionException", "module": "jdk.jdi", "package": "com.sun.jdi.connect.spi", "text": "This exception may be thrown as a result of an asynchronous\n close of a Connection while an I/O operation is\n in progress.\n\n  When a thread is blocked in readPacket waiting for packet from a target VM the\n Connection may be closed asynchronous by another\n thread invokving the close method.\n When this arises the thread in readPacket will throw this\n exception. Similiarly when a thread is blocked in\n Connection.writePacket(byte[]) the Connection may be closed.\n When this occurs the thread in writePacket will throw\n this exception.", "codes": ["public class ClosedConnectionException\nextends IOException"], "fields": [], "methods": []}