{"name": "Class ContextNotEmptyException", "module": "java.naming", "package": "javax.naming", "text": "This exception is thrown when attempting to destroy a context that\n is not empty.\n\n If the program wants to handle this exception in particular, it\n should catch ContextNotEmptyException explicitly before attempting to\n catch NamingException. For example, after catching ContextNotEmptyException,\n the program might try to remove the contents of the context before\n reattempting the destroy.\n \n Synchronization and serialization issues that apply to NamingException\n apply directly here.", "codes": ["public class ContextNotEmptyException\nextends NamingException"], "fields": [], "methods": []}