{"name": "Class JMXServerErrorException", "module": "java.management", "package": "javax.management.remote", "text": "Exception thrown as the result of a remote MBeanServer\n method invocation when an Error is thrown while\n processing the invocation in the remote MBean server.  A\n JMXServerErrorException instance contains the original\n Error that occurred as its cause.", "codes": ["public class JMXServerErrorException\nextends IOException"], "fields": [], "methods": []}