{"name": "Class NamingExceptionEvent", "module": "java.naming", "package": "javax.naming.event", "text": "This class represents an event fired when the procedures/processes\n used to collect information for notifying listeners of\n NamingEvents threw a NamingException.\n This can happen, for example, if the server which the listener is using\n aborts subsequent to the addNamingListener() call.", "codes": ["public class NamingExceptionEvent\nextends EventObject"], "fields": [], "methods": [{"method_name": "getException", "method_sig": "public NamingException getException()", "description": "Retrieves the exception that was thrown."}, {"method_name": "getEventContext", "method_sig": "public EventContext getEventContext()", "description": "Retrieves the EventContext that fired this event.\n This returns the same object as EventObject.getSource()."}, {"method_name": "dispatch", "method_sig": "public void dispatch (NamingListener listener)", "description": "Invokes the namingExceptionThrown() method on\n a listener using this event."}]}