{"name": "Class ServerCloneException", "module": "java.rmi", "package": "java.rmi.server", "text": "A ServerCloneException is thrown if a remote exception occurs\n during the cloning of a UnicastRemoteObject.\n\n As of release 1.4, this exception has been retrofitted to conform to\n the general purpose exception-chaining mechanism.  The \"nested exception\"\n that may be provided at construction time and accessed via the public\n detail field is now known as the cause, and may be\n accessed via the Throwable.getCause() method, as well as\n the aforementioned \"legacy field.\"\n\n Invoking the method Throwable.initCause(Throwable) on an\n instance of ServerCloneException always throws IllegalStateException.", "codes": ["public class ServerCloneException\nextends CloneNotSupportedException"], "fields": [{"field_name": "detail", "field_sig": "public\u00a0Exception detail", "description": "The cause of the exception.\n\n This field predates the general-purpose exception chaining facility.\n The Throwable.getCause() method is now the preferred means of\n obtaining this information."}], "methods": [{"method_name": "getMessage", "method_sig": "public String getMessage()", "description": "Returns the detail message, including the message from the cause, if\n any, of this exception."}, {"method_name": "getCause", "method_sig": "public Throwable getCause()", "description": "Returns the cause of this exception.  This method returns the value\n of the detail field."}]}