{"name": "Class XAException", "module": "java.transaction.xa", "package": "javax.transaction.xa", "text": "The XAException is thrown by the Resource Manager (RM) to inform the\n Transaction Manager of an error encountered by the involved transaction.", "codes": ["public class XAException\nextends Exception"], "fields": [{"field_name": "errorCode", "field_sig": "public\u00a0int errorCode", "description": "The error code with which to create the SystemException."}, {"field_name": "XA_RBBASE", "field_sig": "public static final\u00a0int XA_RBBASE", "description": "The inclusive lower bound of the rollback codes."}, {"field_name": "XA_RBROLLBACK", "field_sig": "public static final\u00a0int XA_RBROLLBACK", "description": "Indicates that the rollback was caused by an unspecified reason."}, {"field_name": "XA_RBCOMMFAIL", "field_sig": "public static final\u00a0int XA_RBCOMMFAIL", "description": "Indicates that the rollback was caused by a communication failure."}, {"field_name": "XA_RBDEADLOCK", "field_sig": "public static final\u00a0int XA_RBDEADLOCK", "description": "A deadlock was detected."}, {"field_name": "XA_RBINTEGRITY", "field_sig": "public static final\u00a0int XA_RBINTEGRITY", "description": "A condition that violates the integrity of the resource was detected."}, {"field_name": "XA_RBOTHER", "field_sig": "public static final\u00a0int XA_RBOTHER", "description": "The resource manager rolled back the transaction branch for a reason\n not on this list."}, {"field_name": "XA_RBPROTO", "field_sig": "public static final\u00a0int XA_RBPROTO", "description": "A protocol error occurred in the resource manager."}, {"field_name": "XA_RBTIMEOUT", "field_sig": "public static final\u00a0int XA_RBTIMEOUT", "description": "A transaction branch took too long."}, {"field_name": "XA_RBTRANSIENT", "field_sig": "public static final\u00a0int XA_RBTRANSIENT", "description": "May retry the transaction branch."}, {"field_name": "XA_RBEND", "field_sig": "public static final\u00a0int XA_RBEND", "description": "The inclusive upper bound of the rollback error code."}, {"field_name": "XA_NOMIGRATE", "field_sig": "public static final\u00a0int XA_NOMIGRATE", "description": "Resumption must occur where the suspension occurred."}, {"field_name": "XA_HEURHAZ", "field_sig": "public static final\u00a0int XA_HEURHAZ", "description": "The transaction branch may have been heuristically completed."}, {"field_name": "XA_HEURCOM", "field_sig": "public static final\u00a0int XA_HEURCOM", "description": "The transaction branch has been heuristically committed."}, {"field_name": "XA_HEURRB", "field_sig": "public static final\u00a0int XA_HEURRB", "description": "The transaction branch has been heuristically rolled back."}, {"field_name": "XA_HEURMIX", "field_sig": "public static final\u00a0int XA_HEURMIX", "description": "The transaction branch has been heuristically committed and\n rolled back."}, {"field_name": "XA_RETRY", "field_sig": "public static final\u00a0int XA_RETRY", "description": "Routine returned with no effect and may be reissued."}, {"field_name": "XA_RDONLY", "field_sig": "public static final\u00a0int XA_RDONLY", "description": "The transaction branch was read-only and has been committed."}, {"field_name": "XAER_ASYNC", "field_sig": "public static final\u00a0int XAER_ASYNC", "description": "There is an asynchronous operation already outstanding."}, {"field_name": "XAER_RMERR", "field_sig": "public static final\u00a0int XAER_RMERR", "description": "A resource manager error has occurred in the transaction branch."}, {"field_name": "XAER_NOTA", "field_sig": "public static final\u00a0int XAER_NOTA", "description": "The XID is not valid."}, {"field_name": "XAER_INVAL", "field_sig": "public static final\u00a0int XAER_INVAL", "description": "Invalid arguments were given."}, {"field_name": "XAER_PROTO", "field_sig": "public static final\u00a0int XAER_PROTO", "description": "Routine was invoked in an inproper context."}, {"field_name": "XAER_RMFAIL", "field_sig": "public static final\u00a0int XAER_RMFAIL", "description": "Resource manager is unavailable."}, {"field_name": "XAER_DUPID", "field_sig": "public static final\u00a0int XAER_DUPID", "description": "The XID already exists."}, {"field_name": "XAER_OUTSIDE", "field_sig": "public static final\u00a0int XAER_OUTSIDE", "description": "The resource manager is doing work outside a global transaction."}], "methods": []}