{"name": "Class XMLSignatureException", "module": "java.xml.crypto", "package": "javax.xml.crypto.dsig", "text": "Indicates an exceptional condition that occurred during the XML\n signature generation or validation process.\n\n An XMLSignatureException can contain a cause: another\n throwable that caused this XMLSignatureException to get thrown.", "codes": ["public class XMLSignatureException\nextends Exception"], "fields": [], "methods": [{"method_name": "getCause", "method_sig": "public Throwable getCause()", "description": "Returns the cause of this XMLSignatureException or\n null if the cause is nonexistent or unknown.  (The\n cause is the throwable that caused this\n XMLSignatureException to get thrown.)"}, {"method_name": "printStackTrace", "method_sig": "public void printStackTrace()", "description": "Prints this XMLSignatureException, its backtrace and\n the cause's backtrace to the standard error stream."}, {"method_name": "printStackTrace", "method_sig": "public void printStackTrace (PrintStream s)", "description": "Prints this XMLSignatureException, its backtrace and\n the cause's backtrace to the specified print stream."}, {"method_name": "printStackTrace", "method_sig": "public void printStackTrace (PrintWriter s)", "description": "Prints this XMLSignatureException, its backtrace and\n the cause's backtrace to the specified print writer."}]}